# Generated by Django 2.2.5 on 2020-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200912_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
