# Generated by Django 2.2.5 on 2020-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_story_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='ips',
            field=models.TextField(default=''),
        ),
    ]
