# Generated by Django 2.2.5 on 2020-09-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_story_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='live_users',
            field=models.TextField(default=''),
        ),
    ]
